-- SQLite
CREATE TABLE AREA
(
  AREA_ID TEXT NOT NULL,
  NAME    TEXT NULL    ,
  PRIMARY KEY (AREA_ID)
);

CREATE TABLE R_SUPPORT
(
  R_SUPPORT_ID TEXT NOT NULL,
  COST         INT  NULL    ,
  PRIMARY KEY (R_SUPPORT_ID)
);

CREATE TABLE SUPPORT
(
  SUPPORT_ID TEXT NOT NULL,
  Y_N        TEXT NULL    ,
  PRIMARY KEY (SUPPORT_ID)
);

CREATE TABLE OBJ1_CARD
(
  OBJ1_ID   NOT NULL,
  CONTENTS  NULL    ,
  PRIMARY KEY (OBJ1_ID)
);

CREATE TABLE OBJ2
(
  OBJ2_ID   NOT NULL,
  CONTENTS  NULL    ,
  PRIMARY KEY (OBJ2_ID)
);

CREATE TABLE GOOD_I
(
  GOOD_I_ID    INT  NOT NULL,
  NAME         TEXT NULL    ,
  PHONE        TEXT NULL    ,
  PLACE        TEXT NULL    ,
  OPENTIME     TEXT NULL    ,
  MENU         TEXT NULL    ,
  AREA_ID      TEXT NOT NULL,
  SUPPORT_ID   TEXT NOT NULL,
  R_SUPPORT_ID TEXT NOT NULL,
  PRIMARY KEY (GOOD_I_ID),
CONSTRAINT FK_AREA_TO_GOOD_I
    FOREIGN KEY (AREA_ID)
    REFERENCES AREA (AREA_ID),
CONSTRAINT FK_SUPPORT_TO_GOOD_I
    FOREIGN KEY (SUPPORT_ID)
    REFERENCES SUPPORT (SUPPORT_ID),
CONSTRAINT FK_R_SUPPORT_TO_GOOD_I
    FOREIGN KEY (R_SUPPORT_ID)
    REFERENCES R_SUPPORT (R_SUPPORT_ID);

);



CREATE TABLE OBJ2_GOOD
(
  OBJ2_ID       NOT NULL,
  GOOD_I_ID INT NOT NULL,
  CONSTRAINT FK_OBJ2_TO_OBJ2_GOOD
    FOREIGN KEY (OBJ2_ID)
    REFERENCES OBJ2 (OBJ2_ID),
CONSTRAINT FK_GOOD_I_TO_OBJ2_GOOD
    FOREIGN KEY (GOOD_I_ID)
    REFERENCES GOOD_I (GOOD_I_ID)
);

CREATE TABLE OBJ_GOOD1
(
  GOOD_I_ID INT NOT NULL,
  OBJ1_ID       NOT NULL,
  CONSTRAINT FK_GOOD_I_TO_OBJ_GOOD1
    FOREIGN KEY (GOOD_I_ID)
    REFERENCES GOOD_I (GOOD_I_ID),
    CONSTRAINT FK_OBJ1_CARD_TO_OBJ_GOOD1
    FOREIGN KEY (OBJ1_ID)
    REFERENCES OBJ1_CARD (OBJ1_ID)
);

