-- SQLite
drop table DEPARTMENT;

create table DEPARTMENT(
ID INT PRIMARY KEY NOT NULL,
DEPT TEXT NOT NULL,
EMP_ID INT NOT NULL);

insert into DEPARTMENT(ID, DEPT, EMP_ID)
values(1,'IT Billing',1);
insert into DEPARTMENT(ID, DEPT, EMP_ID)
values(2,'Engineering',2);
insert into DEPARTMENT(ID, DEPT, EMP_ID)
values(3,'Finance',7);
insert into DEPARTMENT(ID, DEPT, EMP_ID)
values(4,'IT Billing',1);
insert into DEPARTMENT(ID, DEPT, EMP_ID)
values(5,'Finance',7);
insert into COMPANY values(10,'Smith',25,'Texas',35000.00);

create table OLD_COMPANY(
ID TEXT NULL,
NAME TEXT NULL,
AGE INT NULL,
ADDRESS TEXT NULL,
SALARY INT NULL);

insert into OLD_COMPANY
select * from COMPANY
where NAME=='Paul';

--! JOIN 
--CROSS JOIN
select COMPANY.*,DEPARTMENT.* from company cross join DEPARTMENT;

--INNER JOIN
-- on 이 where 역할  !!
select EMP_ID,NAME,DEPT from COMPANY
inner join DEPARTMENT on COMPANY.ID=DEPARTMENT.ID;

--OUTER JOIN
select COMPANY.ID,COMPANY.NAME,DEPARTMENT.DEPT from COMPANY
left outer join DEPARTMENT
on COMPANY.ID=DEPARTMENT.EMP_ID;

select COMPANY.ID,COMPANY.NAME,OLD_COMPANY.NAME from COMPANY
left outer join OLD_COMPANY
on COMPANY.ID=OLD_COMPANY.ID;

select COMP.NAME,AGE,DEPT,EMP_ID from
(select *from COMPANY where SALARY>2000) as COMP
left outer join DEPARTMENT on COMP.ID=DEPARTMENT.EMP_ID;

--UNION

--query1 5개
select EMP_ID,NAME,DEPT FROM COMPANY inner join DEPARTMENT
on COMPANY.ID=DEPARTMENT.EMP_ID;
--query2  16개
SELECT EMP_ID,NAME,DEPT from COMPANY left outer join DEPARTMENT
on COMPANY.ID=DEPARTMENT.EMP_ID;

--UNION 1,2  중복제거후 결과>>10개
select EMP_ID,NAME,DEPT FROM COMPANY inner join DEPARTMENT
on COMPANY.ID=DEPARTMENT.EMP_ID
UNION
SELECT EMP_ID,NAME,DEPT from COMPANY left outer join DEPARTMENT
on COMPANY.ID=DEPARTMENT.EMP_ID;

--UNION ALL 
SELECT EMP_ID, NAME, DEPT FROM COMPANY INNER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.EMP_ID 
UNION ALL
SELECT EMP_ID, NAME, DEPT FROM COMPANY LEFT OUTER JOIN DEPARTMENT   ON COMPANY.ID = DEPARTMENT.EMP_ID;

--CREATE VIEW
CREATE VIEW COMPANY_VIEW AS SELECT ID, NAME, AGE FROM  COMPANY; 
--DROP으로 VIEW 제거
--DROP VIEW COMPANY_VIEW;

--CASE

select ID, max(NAME) as NAME,ADDRESS, 
--max를 걸지않으면 db가 선택한 것에서 if문 작동
--컬럼 1개
CASE 
WHEN NAME=='Paul' THEN SALARY END AS NAME01_CASE,
--컬럼 1개
CASE
WHEN NAME=='David' THEN AGE END AS NAME02_CASE
from COMPANY group by ADDRESS;












