-- SQLite
CREATE TABLE IMG
(
  IMG_ID   TEXT NOT NULL,
  M_B_ID   TEXT NOT NULL,
  CONTENTS TEXT NULL    ,
  PRIMARY KEY (IMG_ID),
  CONSTRAINT FK_MULTI_BOARD_TO_IMG
    FOREIGN KEY (M_B_ID)
    REFERENCES MULTI_BOARD (M_B_ID)
);

CREATE TABLE MULTI_BOARD
(
  M_B_ID    TEXT NOT NULL,
  MEMBER_ID TEXT NOT NULL,
  M_NAME    TEXT NULL    ,
  GENRE     TEXT NULL    ,
  PRIMARY KEY (M_B_ID),
  CONSTRAINT FK_MEMBER2_TO_MULTI_BOARD
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER2 (MEMBER_ID)

);

);
--IMG


