select STORE_ID,STORE_NAME,OWNER,TEL,ADDRESS,LOCATION.PROVINCE_NAME,BENEFIT_PERSONELL.AMOUNT_OF_PERSONELL,DONATION_GENERAL.PATICIPATION,BENEFIT_MENU.MENU_TYPE,ROUTINAL_DONATION.DONATION_AMOUNT
from GOOD_STORE
--LOCATION JOIN
left outer join LOCATION
on GOOD_STORE.PROVINCE_ID=LOCATION.PROVINCE_ID
--B.P JOIN
left outer join BENEFIT_PERSONELL
on GOOD_STORE.PERSONELL_ID=BENEFIT_PERSONELL.PERSONELL_ID
--MENU
left outer join BENEFIT_MENU
on GOOD_STORE.MENTYPE_ID=BENEFIT_MENU.MENTYPE_ID
--
left outer join ROUTINAL_DONATION
on GOOD_STORE.DONATION_ID=ROUTINAL_DONATION.DONATION_ID
--
left outer join DONATION_GENERAL
on GOOD_STORE.PARTICIPATE_ID=DONATION_GENERAL.PARTICIPATE_ID;