CREATE TABLE COMPANY(
ID INT  NOT NULL,
NAME TEXT NOT NULL,
AGE INT NOT NULL,
ADDRESS TEXT NULL,
SALARY INT NOT NULL
);

INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Paul', 32, 'California', 20000.00 );

INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Allen', 25, 'Texas', 15000.00 );

INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'Teddy', 23, 'Norway', 20000.00 );

INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Mark', 25, 'Rich-Mond ', 65000.00 );

INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'David', 27, 'Texas', 85000.00 );

INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Kim', 22, 'South-Hall', 45000.00 );
INSERT INTO COMPANY VALUES (7, 'James', 24, 'Houston', 10000.00 );
INSERT INTO COMPANY VALUES (8, 'James', 35, 'Texas', 40000.00 );

변경
alter table COMPANY rename to OLD_COMPANY;

alter table OLD_COMPANY add column GENDER;

drop table COMPANY;

CREATE TABLE COMPANY(
ID INT  NOT NULL,
NAME TEXT NOT NULL,
AGE INT NOT NULL,
ADDRESS TEXT NULL,
SALARY INT NOT NULL
);

insert into COMPANY(ID,NAME,AGE,ADDRESS,SALARY)
select * from OLD_COMPANY;

update COMPANY
set SALARY=10000
where NAME in (select NAME from COMPANY where NAME == 'Paul'); 

select *from COMPANY where AGE is not NULL;
select *from COMPANY where name like 'P__l';

select *from COMPANY where NAME like '_a%';

select *from COMPANY where AGE IN (25,27);

INSERT INTO COMPANY VALUES (7, 'Paul', 24, 'Houston', 15000.00 );
INSERT INTO COMPANY VALUES (8, 'James', 35, 'Texas', 30000.00 );

select *from COMPANY order by SALARY desc;

select NAME, sum(SALARY) from COMPANY;

select *from COMPANY where AGE>=25 and SALARY>=65000;

select NAME,SALARY from COMPANY group by NAME;

SELECT NAME, SUM(SALARY) FROM COMPANY GROUP BY NAME ORDER BY NAME desc;

