select *from COURSE;

select *from MEMBER;
select *from AUTHORITY_MEMBER;
select *from AUTHORITY;
select *from COMMONCODE;


--권한이 'ROLE_STUDENT’을 가진 목록 : AUTHORITY_MEMBER
select MEMBER.MEMBER_SEQ,MEMBER.MEMBER_ID,MEMBER.NAME,DP.AUTHORITY_ID from (select *from AUTHORITY_MEMBER where AUTHORITY_ID='ROLE_STUDENT') as DP inner join MEMBER
on MEMBER.MEMBER_SEQ = DP.MEMBER_SEQ;


select *from AUTHORITY_MEMBER where AUTHORITY_ID='ROLE_STUDENT';

--강의,강연 신 조직구조 확인

select *from COURSE;
select *from ORGANIZATION;

select CP.ORGANIZATION_SEQ,CP.NAME,COURSE.COURSE_SEQ,COURSE.TITLE from (select *from ORGANIZATION where ORGANIZATION.NAME='강의/강연 신')
as CP inner join COURSE on CP.ORGANIZATION_SEQ=COURSE.ORGANIZATION_SEQ;
--15개
select count(*) from (select *from ORGANIZATION where ORGANIZATION.NAME='강의/강연 신')
as CP inner join COURSE on CP.ORGANIZATION_SEQ=COURSE.ORGANIZATION_SEQ;

--15개
select count(*) from COURSE
where COURSE.ORGANIZATION_SEQ='UUID-ORGANIZATION-YOJULAB';
--맞는듯


select MEMBER.NAME,MEMBER.MEMBER_ID,AUTHORITY.AUTHORITY_ID from MEMBER inner join AUTHORITY_MEMBER on MEMBER.MEMBER_SEQ=AUTHORITY_MEMBER.MEMBER_SEQ
inner join AUTHORITY on AUTHORITY.AUTHORITY_ID=AUTHORITY_MEMBER.AUTHORITY_ID;

inner join (select * from AUTHORITY where AUTHORITY.AUTHORITY_ID='ROLE_STUDENT') as DP on DP.AUTHORITY_ID=AUTHORITY_MEMBER.AUTHORITY_ID;

--1번문제
select MEMBER.NAME, MEMBER.MEMBER_ID, DP.AUTHORITY_ID, TP.NAME from MEMBER inner join AUTHORITY_MEMBER on MEMBER.MEMBER_SEQ=AUTHORITY_MEMBER.MEMBER_SEQ
inner join (select * from AUTHORITY where AUTHORITY.AUTHORITY_ID='ROLE_STUDENT') as DP on DP.AUTHORITY_ID=AUTHORITY_MEMBER.AUTHORITY_ID;
--COMMONCODE table의 COMMONCODE_ID column의  T_YN_NO record에 앞의것 대응 1:1로(record 더 필요하면 추가 join)

--2번문제
select *from ORGANIZATION;
select *from COURSE;
select AP.NAME, COURSE.TITLE from (select *from ORGANIZATION where ORGANIZATION.NAME='강의/강연 신')
as AP inner join COURSE on AP.ORGANIZATION_SEQ=COURSE.ORGANIZATION_SEQ;

select *from ORGANIZATION where ORGANIZATION.NAME='강의/강연 신';